name: CI

on:
  push:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: yarnpkg/node-yarn
    steps:
      - name: Run a multi-line script
        run: |
          yarn
          yarn build
