name: Cicd

on:
  push:
    branches: [ 'master' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Build
        run: |
          yarn
          yarn build
          
      - name: E2E tests
        run: |
          yarn testE2e
          
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: |
            lib
            package.json
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          always-auth: true
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
