name: Cicd

on:
  push:
    branches: [ 'payments' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Build
        run: |
          yarn
          yarn build
          
      - name: E2E tests
        run: |
          yarn hardhat node &
          sleep 5
          yarn testE2e
